version: '3'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env.backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - frontend/.env.frontend
    depends_on:
      - backend
    ports:
      - "9000:80"
    